FROM python:3.9.6

COPY . /opt/app

WORKDIR /opt/app

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - && \
    export PATH=$HOME/.poetry/bin:$PATH && \
    echo "export PATH=$HOME/.poetry/bin:$PATH" >> $HOME/.bashrc && \
    cd /opt/app && \
    poetry install --no-dev && \
    chmod +x entrypoint.sh

ENTRYPOINT [ "/opt/app/entrypoint.sh" ]