# Generated by Django 3.2.6 on 2021-08-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'weather',
                'verbose_name_plural': 'weathers',
                'db_table': 'weather',
            },
        ),
    ]
