# Generated by Django 3.2.6 on 2021-08-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20210825_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocean',
            fields=[
                ('ocean_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ocean',
                'verbose_name_plural': 'oceans',
                'db_table': 'ocean',
            },
        ),
    ]
