# Generated by Django 3.2.6 on 2021-08-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
        ),
        migrations.AlterField(
            model_name='location',
            name='ocean',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.ocean'),
        ),
    ]
