# Generated by Django 3.2.6 on 2021-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20210825_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'weather',
                'verbose_name_plural': 'weathers',
                'db_table': 'weather',
            },
        ),
    ]
