# Generated by Django 3.2.6 on 2021-08-25 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('measure_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('measure_num', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measured_at', models.DateTimeField()),
                ('tz_timestamp', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)])),
                ('wind_gust', models.FloatField()),
                ('visibility', models.IntegerField()),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('sea_level', models.IntegerField()),
                ('ground_level', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weather')),
            ],
            options={
                'verbose_name': 'measure',
                'verbose_name_plural': 'measures',
                'db_table': 'measure',
            },
        ),
    ]
