# Generated by Django 3.2.6 on 2021-08-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='wind_gust',
            field=models.FloatField(null=True),
        ),
    ]
