name: CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.9.6
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.7

      - name: Init environment
        run: |
          cp .env-example .env
          poetry install
          poetry run python manage.py migrate
        
      - name: Run tests
        run: poetry run pytest